server:
  port: ${PORT:5000}
spring:
  datasource:
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
jestify-app:
  token:
    access_lifetime_minutes: ${ACCESS_TOKEN_LIFE_TIME_MINUTES}
    refresh_lifetime_minutes: ${REFRESH_TOKEN_LIFE_TIME_MINUTES}
  remember_me:
    expired_days: ${REMEMBER_ME_DAYS}