server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jestify
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jestify-app:
  token:
    access_lifetime_minutes: 100
    refresh_lifetime_minutes: 1440
  remember_me:
    expired_days: 30